# Generated by Django 5.0 on 2023-12-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_problema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=30)),
                ('articulo', models.CharField(max_length=200)),
                ('monto', models.CharField(max_length=10)),
            ],
        ),
    ]
