# Generated by Django 5.0 on 2023-12-20 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_fiado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
